"""Gera a versao em portugues do diagrama a partir da inglesa.

Um mapa de traducao em vez de um segundo arquivo escrito a mao: quando o
diagrama muda, muda so o ingles e esta lista, e as duas versoes nao divergem.
"""

from pathlib import Path

ORIGEM = Path(__file__).with_name("architecture.html")
DESTINO = Path(__file__).with_name("architecture.pt-BR.html")

TRADUCAO = [
    # ------------------------------------------------------------ cabecalho
    ("<title>RAG Agent Architecture</title>", "<title>Arquitetura do RAG Agent</title>"),
    ('<html lang="en">', '<html lang="pt-BR">'),
    (
        "Agentic retrieval over your own documents ·",
        "Recuperação agêntica sobre os seus próprios documentos ·",
    ),
    ("<b>hybrid search</b>", "<b>busca híbrida</b>"),
    ("<b>six graded metrics</b>", "<b>seis métricas medidas</b>"),
    ("<b>guardrails on both sides</b>", "<b>guardrails nos dois lados</b>"),
    # ---------------------------------------------------------------- faixas
    ("<span>Build</span>", "<span>Construção</span>"),
    ("<span>Serve</span>", "<span>Operação</span>"),
    # -------------------------------------------------------------- ingestao
    (
        "<h3>Ingestion and storage <em>offline · rag ingest</em></h3>",
        "<h3>Ingestão e armazenamento <em>offline · rag ingest</em></h3>",
    ),
    ('<div class="t">Load</div>', '<div class="t">Carregar</div>'),
    ("<div class=\"w\">pdf, md, txt</div>", '<div class="w">pdf, md, txt</div>'),
    ('<div class="t">Split<span class="tag tag-m">measured</span></div>',
     '<div class="t">Quebrar<span class="tag tag-m">medido</span></div>'),
    ('<div class="w">by article, beat by character</div>',
     '<div class="w">por artigo, melhor que por caractere</div>'),
    ('<div class="t">Scan corpus</div>', '<div class="t">Varrer o corpus</div>'),
    ('<div class="w">indirect injection</div>', '<div class="w">injeção indireta</div>'),
    ('<div class="t">Embed</div>', '<div class="t">Vetorizar</div>'),
    ('<div class="w">1536 dimensions</div>', '<div class="w">1536 dimensões</div>'),
    ('<div class="t">Store</div>', '<div class="t">Armazenar</div>'),
    ('<div class="w">one transaction</div>', '<div class="w">uma transação</div>'),
    ('<div class="t">Index</div>', '<div class="t">Indexar</div>'),
    ('<div class="w">vector and text</div>', '<div class="w">vetor e texto</div>'),
    ('<div class="t">Idempotent by construction</div>',
     '<div class="t">Idempotente por construção</div>'),
    ("re-ingesting overwrites · a queue may redeliver · rag sources --remove takes one document out",
     "reindexar sobrescreve · uma fila pode reentregar · rag sources --remove tira um documento"),
    # ------------------------------------------------------------ recuperacao
    ("<h3>Retrieval <em>two retrievers, one ranking</em></h3>",
     "<h3>Recuperação <em>dois recuperadores, uma ordenação</em></h3>"),
    ('<div class="t">Vector search</div>', '<div class="t">Busca vetorial</div>'),
    ('<div class="w">meaning · follows a paraphrase</div>',
     '<div class="w">significado · acompanha paráfrase</div>'),
    ('<div class="t">Keyword search</div>', '<div class="t">Busca por palavra</div>'),
    ('<div class="w">identity · finds exact codes and references</div>',
     '<div class="w">identidade · acha códigos e referências exatas</div>'),
    ('<div class="t">RRF fusion<span class="tag tag-m">measured</span></div>',
     '<div class="t">Fusão RRF<span class="tag tag-m">medido</span></div>'),
    ('<div class="w">merges on rank, not score · pulled the missing passage into the window</div>',
     '<div class="w">funde por posição, não por nota · trouxe o trecho que faltava para a janela</div>'),
    ('<div class="t">Reranking<span class="tag tag-o">OFF</span></div>',
     '<div class="t">Reordenação<span class="tag tag-o">DESLIGADA</span></div>'),
    ('<div class="w">fixes precision; the gap here was recall</div>',
     '<div class="w">corrige precisão; aqui faltava recall</div>'),
    # -------------------------------------------------------------- avaliacao
    ("<h3>Evaluation <em>rag eval · graded questions, some unanswerable</em></h3>",
     "<h3>Avaliação <em>rag eval · perguntas medidas, algumas sem resposta</em></h3>"),
    ('<div class="t">Reference based</div>', '<div class="t">Com referência</div>'),
    ('<div class="w">against the expected answer</div>',
     '<div class="w">contra a resposta esperada</div>'),
    ('<div class="t">Reference free</div>', '<div class="t">Sem referência</div>'),
    ('<div class="w">against what was retrieved</div>',
     '<div class="w">contra o que foi recuperado</div>'),
    ('<div class="t">Gate</div>', '<div class="t">Portão</div>'),
    ('<div class="w">the exit code is the contract</div>',
     '<div class="w">o código de saída é o contrato</div>'),
    # ----------------------------------------------------------------- servir
    ("<h3>Answering a question <em>online · CLI and HTTP, one service layer</em></h3>",
     "<h3>Respondendo uma pergunta <em>online · CLI e HTTP, uma camada de serviço</em></h3>"),
    ('<div class="t">Guardrails in</div>', '<div class="t">Guardrails na entrada</div>'),
    ('<div class="w">length · CPF · CNPJ · keys · injection</div>',
     '<div class="w">tamanho · CPF · CNPJ · chaves · injeção</div>'),
    ('<div class="t">Agent</div>', '<div class="t">Agente</div>'),
    ('<div class="w">model ⇄ tools · 3 searches per turn</div>',
     '<div class="w">modelo ⇄ ferramentas · buscas com teto por turno</div>'),
    ('<div class="t">Retrieve</div>', '<div class="t">Recuperar</div>'),
    ('<div class="m mono">hybrid, fused</div>', '<div class="m mono">híbrida, fundida</div>'),
    ('<div class="w">the panel above</div>', '<div class="w">o painel acima</div>'),
    ('<div class="t">Answer</div>', '<div class="t">Responder</div>'),
    ('<div class="w">cited, or an honest refusal</div>',
     '<div class="w">com fonte, ou uma recusa honesta</div>'),
    ('<div class="t">Guardrails out</div>', '<div class="t">Guardrails na saída</div>'),
    ('<div class="m mono">citation · token ceiling</div>',
     '<div class="m mono">citação · teto de tokens</div>'),
    ('<div class="w">records, never blocks</div>', '<div class="w">registra, nunca bloqueia</div>'),
    ('<div class="t">One service layer, and it knows about neither</div>',
     '<div class="t">Uma camada de serviço, e ela não conhece nenhuma das duas</div>'),
    ("agent/service.py holds the turn · the CLI and the API translate in and out · the guardrails run here, so a third interface is covered by construction",
     "agent/service.py conduz o turno · o CLI e a API traduzem entrada e saída · os guardrails rodam aqui, então uma terceira interface já nasce coberta"),
    ('<div class="t">A refusal is not a failure</div>',
     '<div class="t">Recusa não é falha</div>'),
    ("CLI: a yellow line and exit code 2 · HTTP: 400 with the reason in its own field · 500 would page someone for a guardrail doing its job",
     "CLI: uma linha amarela e código de saída 2 · HTTP: 400 com o motivo em campo próprio · 500 acordaria o plantão por um guardrail funcionando"),
    # ------------------------------------------------------------- operar
    ("<h3>Operating it <em>FastAPI · Uvicorn · Redis</em></h3>",
     "<h3>Operação <em>FastAPI · Uvicorn · Redis</em></h3>"),
    ('<span class="k">Tracing</span>', '<span class="k">Rastreamento</span>'),
    ("Langfuse: every turn, its tools, its tokens and its cost",
     "Langfuse: cada turno, suas ferramentas, seus tokens e seu custo"),
    ('<span class="k">Probes</span>', '<span class="k">Sondas</span>'),
    ("<code>/health</code> liveness, checks nothing else · <code>/ready</code> readiness, checks the database and the index",
     "<code>/health</code> vivacidade, não checa mais nada · <code>/ready</code> prontidão, checa o banco e o índice"),
    ('<span class="k">Rate limit</span>', '<span class="k">Limite de taxa</span>'),
    ("moving window per caller, shared through Redis so workers keep one ceiling",
     "janela móvel por chamador, compartilhada no Redis para os workers terem um teto só"),
    ('<span class="k">Concurrency</span>', '<span class="k">Concorrência</span>'),
    ("Uvicorn workers · sessions in Redis, message history only",
     "workers do Uvicorn · sessões no Redis, só o histórico de mensagens"),
    ('<span class="k">Failure</span>', '<span class="k">Falha</span>'),
    ("every message names the command that fixes it",
     "toda mensagem nomeia o comando que resolve"),
    # -------------------------------------------------------------- governanca
    ("<h2>LLM<br>Governance</h2>", "<h2>Governança<br>de LLM</h2>"),
    ('<div class="t">Prompt management</div>', '<div class="t">Gestão de prompts</div>'),
    ("Four prompts in Langfuse under a <code>production</code> label. Moving the label is a rollback with no deploy. Falls back to <code>templates.py</code>.",
     "Quatro prompts no Langfuse sob o label <code>production</code>. Mover o label é um rollback sem deploy. Cai para <code>templates.py</code>."),
    ('<div class="t">Safety policy</div>', '<div class="t">Política de segurança</div>'),
    ("Refused before it costs: injection, CPF, CNPJ, API keys. Flagged after it is paid for: a missing citation.",
     "Recusado antes de custar: injeção, CPF, CNPJ, chaves de API. Registrado depois de pago: resposta sem fonte."),
    ('<div class="t">Schema control</div>', '<div class="t">Controle de esquema</div>'),
    ("Alembic owns the schema. The application checks and refuses, naming <code>alembic upgrade head</code>. It never migrates itself.",
     "O esquema é do Alembic. A aplicação verifica e recusa, nomeando <code>alembic upgrade head</code>. Ela nunca migra sozinha."),
    ('<div class="t">Reproducibility</div>', '<div class="t">Reprodutibilidade</div>'),
    ("Every run records its model, chunking, <code>RETRIEVAL_K</code> and prompt hash. A score without them compares to nothing.",
     "Cada execução grava modelo, chunking, <code>RETRIEVAL_K</code> e o hash do prompt. Uma nota sem isso não se compara a nada."),
    ('<div class="t">Cost control</div>', '<div class="t">Controle de custo</div>'),
    ("Per-answer estimate, a token ceiling, a search budget per turn, and <code>--max-cost</code> on the suite.",
     "Estimativa por resposta, teto de tokens, orçamento de buscas por turno e <code>--max-cost</code> na suíte."),
    ('<div class="t">Audit</div>', '<div class="t">Auditoria</div>'),
    ("Question, retrieved passages and answer are one trace. Rotating local logs keep what the platform does not.",
     "Pergunta, trechos recuperados e resposta são um trace só. O log local rotativo guarda o que a plataforma não guarda."),
    ("Not covered yet: permission-aware retrieval, and scanning the answer for personal data.",
     "Ainda não coberto: recuperação com permissão, e varredura de dado pessoal na resposta."),
    # ----------------------------------------------------------- raia llmops
    ("<h3>Quality gates <em>every push</em></h3>",
     "<h3>Portões de qualidade <em>a cada push</em></h3>"),
    ('<div class="t">Tests</div>', '<div class="t">Testes</div>'),
    ('<div class="w">unit with no infrastructure, integration behind a mark</div>',
     '<div class="w">unidade sem infraestrutura, integração atrás de uma marca</div>'),
    ('<div class="t">Static checks</div>', '<div class="t">Checagem estática</div>'),
    ('<div class="w">lint, format and types, all strict</div>',
     '<div class="w">lint, formatação e tipos, tudo estrito</div>'),
    ('<div class="t">Coverage</div>', '<div class="t">Cobertura</div>'),
    ('<div class="w">reported per module, not as one number</div>',
     '<div class="w">por módulo, não como um número só</div>'),

    ("<h3>Delivery <em>the same artefact everywhere</em></h3>",
     "<h3>Entrega <em>o mesmo artefato em todo lugar</em></h3>"),
    ('<div class="w">Linux and Windows, so a platform break shows here</div>',
     '<div class="w">Linux e Windows, para uma quebra de plataforma aparecer aqui</div>'),
    ('<div class="t">Image</div>', '<div class="t">Imagem</div>'),
    ('<div class="w">non-root · CPU-only torch · serves and migrates</div>',
     '<div class="w">sem root · torch só de CPU · serve e migra</div>'),
    ('<div class="t">Migrate</div>', '<div class="t">Migrar</div>'),
    ('<div class="w">one shot before the API, never at boot</div>',
     '<div class="w">uma tacada antes da API, nunca no boot</div>'),

    ("<h3>Continuous evaluation <em>on demand and weekly</em></h3>",
     "<h3>Avaliação contínua <em>sob demanda e semanal</em></h3>"),
    ('<div class="t">Scheduled run</div>', '<div class="t">Execução agendada</div>'),
    ('<div class="m mono">cron · Mondays</div>', '<div class="m mono">cron · segundas</div>'),
    ('<div class="w">the corpus stops changing; the model does not</div>',
     '<div class="w">o corpus para de mudar; o modelo não</div>'),
    ('<div class="t">Compare</div>', '<div class="t">Comparar</div>'),
    ('<div class="w">what moved, and which setting moved with it</div>',
     '<div class="w">o que mudou, e qual configuração mudou junto</div>'),
    ('<div class="t">Fail the build</div>', '<div class="t">Reprovar a build</div>'),
    ('<div class="m mono">score and cost thresholds</div>',
     '<div class="m mono">limiares de nota e custo</div>'),
    ('<div class="w">a regression blocks; one known failure does not</div>',
     '<div class="w">uma regressão bloqueia; uma falha conhecida não</div>'),
]

texto = ORIGEM.read_text(encoding="utf-8")
faltando = [ingles for ingles, _ in TRADUCAO if ingles not in texto]

for ingles, portugues in TRADUCAO:
    texto = texto.replace(ingles, portugues)

DESTINO.write_text(texto, encoding="utf-8")

print("nao encontrados no original:", faltando or "nenhum")
print("gerado:", DESTINO.name)
